from backend.modules.platform import controller
from backend.utils.routing import ID

ROUTES = [
    ('GET',   '/api/platform/registration',   controller.registration_settings,      'platform'),
    ('POST',  '/api/platform/registration',   controller.save_registration_settings, 'platform'),
    ('GET',   '/api/platform/sms',            controller.sms_settings,               'platform'),
    ('POST',  '/api/platform/sms',            controller.save_sms_settings,          'platform'),
    ('POST',  '/api/platform/sms/test',       controller.test_sms,                   'platform'),
    ('GET',   '/api/platform/turnstile',      controller.turnstile_settings,         'platform'),
    ('POST',  '/api/platform/turnstile',      controller.save_turnstile_settings,    'platform'),
    ('GET',   '/api/platform/tenants',        controller.list_tenants,               'platform'),
    ('POST',  '/api/platform/tenants',        controller.create_tenant,              'platform'),
    ('PATCH', f'/api/platform/tenants/{ID}',  controller.set_tenant_status,          'platform'),
    ('PATCH', f'/api/platform/tenants/{ID}/quota', controller.set_tenant_quota,      'platform'),
    ('PATCH', f'/api/platform/tenants/{ID}/features', controller.set_tenant_feature, 'platform'),
    ('PATCH', f'/api/platform/tenants/{ID}/slug', controller.rename_tenant_slug,     'platform'),
    ('POST',  f'/api/platform/tenants/{ID}/admins', controller.add_admin,          'platform'),
    # Its staff and whether each has two-step sign-in; resetting one who lost their phone (staff_security).
    ('GET',   f'/api/platform/tenants/{ID}/members', controller.tenant_members,      'platform'),
    ('POST',  f'/api/platform/users/{ID}/reset-security', controller.reset_security, 'platform'),
    # Any account by its email, staff or customer: suspended everywhere, or its password made to change (accounts.py).
    ('POST',  '/api/platform/accounts/search', controller.search_accounts,           'platform'),
    ('POST',  f'/api/platform/accounts/(staff|customer)/{ID}/suspend', controller.suspend_account, 'platform'),
    ('POST',  f'/api/platform/accounts/(staff|customer)/{ID}/force-reset', controller.force_password_reset, 'platform'),
    # ปิดองค์กรถาวร (closing.py): the whole organization exported for its owner, then deleted for good.
    ('GET',   f'/api/platform/tenants/{ID}/export', controller.export_tenant,        'platform'),
    ('DELETE',f'/api/platform/tenants/{ID}',  controller.close_tenant,               'platform'),
    # องค์กรที่หลับ (dormant.py): nobody in for 90 days and no new case; emailing their owners.
    ('GET',   '/api/platform/dormant',        controller.dormant_tenants,            'platform'),
    ('POST',  f'/api/platform/tenants/{ID}/contact', controller.contact_tenant,      'platform'),
    ('GET',   '/api/platform/system',         controller.system,                     'platform'),
    ('GET',   '/api/platform/health',         controller.health,                     'platform'),
    ('POST',  '/api/platform/checklist/key-saved', controller.key_saved,             'platform'),
    ('GET',   '/api/platform/notifications',  controller.notifications,              'platform'),
    ('POST',  f'/api/platform/tenants/{ID}/channels/retry', controller.retry_channels, 'platform'),
    ('GET',   '/api/platform/backups',        controller.backups,                    'platform'),
    ('POST',  '/api/platform/backups',        controller.run_backup,                 'platform'),
    ('POST',  '/api/platform/backups/settings', controller.save_backup_settings,     'platform'),
    # A copy of every backup away from this machine (offsite.py): where, a test, and sending the newest now.
    ('POST',  '/api/platform/backups/offsite', controller.save_offsite,              'platform'),
    ('POST',  '/api/platform/backups/offsite/test', controller.test_offsite,         'platform'),
    ('POST',  '/api/platform/backups/offsite/send', controller.send_offsite,         'platform'),
    ('GET',   r'/api/platform/backups/(bookdose-(?:auto|manual|upload|before)-\d{8}-\d{6}\.zip)', controller.download_backup, 'platform'),
    # Restoring from the console (restore.py): a backup sent in pieces, what restoring it would replace, and the restore.
    ('POST',  '/api/platform/restore/upload', controller.upload_backup,          'platform'),
    # The libraries checked against the published vulnerabilities (vulns.py): once a day, or now.
    ('GET',   '/api/platform/vulns',          controller.vulnerabilities,        'platform'),
    ('POST',  '/api/platform/vulns',          controller.scan_vulnerabilities,   'platform'),
    ('POST',  '/api/platform/restore/preview', controller.restore_preview,       'platform'),
    ('POST',  '/api/platform/restore',        controller.restore_backup,         'platform'),
    ('GET',   '/api/platform/announcement',   controller.announcement,               'platform'),
    ('POST',  '/api/platform/announcement',   controller.save_announcement,          'platform'),
    ('DELETE','/api/platform/announcement',   controller.clear_announcement,         'platform'),
    ('GET',   '/api/platform/admins',         controller.platform_team,              'platform'),
    ('POST',  '/api/platform/admins',         controller.add_platform_admin,         'platform'),
    ('DELETE',f'/api/platform/admins/{ID}',   controller.remove_platform_admin,      'platform'),
    ('GET',   '/api/platform/faq',            controller.global_faq,                 'platform'),
    ('POST',  '/api/platform/faq',            controller.create_global_article,      'platform'),
    ('PATCH', f'/api/platform/faq/{ID}',      controller.update_global_article,      'platform'),
    ('DELETE',f'/api/platform/faq/{ID}',      controller.delete_global_article,      'platform'),
    ('POST',  f'/api/platform/faq/{ID}/publish',   controller.publish_global_article,   'platform'),
    ('POST',  f'/api/platform/faq/{ID}/unpublish', controller.unpublish_global_article, 'platform'),
    ('DELETE',f'/api/platform/faq/{ID}/changes',   controller.discard_global_changes,   'platform'),
    ('GET',   '/api/platform/reports',        controller.problem_reports,            'platform'),
    ('PATCH', f'/api/platform/reports/{ID}',  controller.set_report_status,          'platform'),
    ('GET',   '/api/platform/templates',      controller.article_templates,          'platform'),
    ('POST',  '/api/platform/templates',      controller.create_article_template,    'platform'),
    ('PATCH', f'/api/platform/templates/{ID}', controller.update_article_template,   'platform'),
    ('POST',  f'/api/platform/templates/{ID}/publish', controller.publish_article_template, 'platform'),
    ('DELETE',f'/api/platform/templates/{ID}', controller.delete_article_template,   'platform'),
    # The status page: no sign-in, because somebody who cannot sign in is exactly who needs to read it.
    ('GET',   '/api/status',                  controller.status,                     'public'),
    ('POST',  '/api/platform/status',         controller.save_status_notice,         'platform'),
    ('DELETE','/api/platform/status',         controller.clear_status_notice,        'platform'),
    ('GET',   '/api/guides',                  controller.guides,                     'account'),
    ('POST',  '/api/problem-reports',         controller.report_problem,             'account'),
]
